### ISSUE TITLE
How to add a dependency to the gatling task?

### ISSUE THREAD

**Issue by christianhuening** [lkishalmi/gradle-gatling-plugin#24]
I'd like to add a dependency to the call of "gatling". In this case I want to start a MongoDB prior to executing Gatling. However
`gatling.dependsOn startManagedMongoDb`
or
`gatling {}.doFirst(startManagedMongoDb)`

do not work. The error states that the method could not be found  on the extension object.
What can I do to make this work?

**Comment by eshepelyuk** [comment]
What about smth like 
```
tasks['gatling'].dependsOn ....
```

**Comment by eshepelyuk** [comment]
@lkishalmi to avoid such confusing, I'd suggest to rename `gatling` task and `gatling-FQN` alias to smth like `gatlingRun`. If you agree - I can create a new issue for this.

**Comment by christianhuening** [comment]
Thanks for the hint, but sadly it's still not working. I tried
`    tasks['gatling']...`
and 
`    tasks.getByName('gatling')...`

but I still get the error that there is no such task in my project:

> Build file (...)\Application\booking-service\build.gradle' line: 63
> 
> * What went wrong:
> A problem occurred evaluating root project 'booking-service'.
> > Task with name 'gatling' not found in root project 'booking-service'.

whereas `gradlew tasks` shows that task "gatling" is there.

**Comment by eshepelyuk** [comment]
Yeah, you're right. It's my mistake. The issue happens because `gatling` task ain't created immediately after plugin application, but via `project.afterEvaluate { ...}` method instead.

So, when you try to find it, you currently fail, because task doesn't exist. 
I'd advice to play around with delayed evaluation methods of  `project` object.

Additionaly, could you please create a new issue to clearly explain and resolve the problem without the need to hack on `Gradle` API.

**Comment by christianhuening** [comment]
well actually the following finally worked:
`project.afterEvaluate { Project p -> p.getTasks().getByName('gatling').dependsOn(startManagedMongoDb) }`

However I don't quite get what you want me to do in regard to the new issue, sorry?!

**Comment by eshepelyuk** [comment]
Plz check #25
