### ISSUE TITLE
jvmArgs extension property doesn't work in 0.4.1

### ISSUE THREAD

**Issue by ashlineldridge** [lkishalmi/gradle-gatling-plugin#33]
The `gatling` extension property `jvmArgs` appears to be broken in 0.4.1.

I think this is due to line 46: `jvmArgs = self.getJvmArgs()` in `GatlingRunTask`. The instance variable `List<String> jvmArgs` is not being used - rather the JVM args are being pulled from the `JavaExec` base class.

This can be illustrated by the following `gatling` extension set up:

```
gatling {
  jvmArgs = [  '-Dfoo.bar=baz' ]
}
```

And then inserting the following Scala code at the beginning of a simulation:

```
import scala.collection.JavaConverters._
System.getProperties.asScala.foreach {
    case (k, v) if k.startsWith("foo") => logger.info(s"K: ${k}, V: ${v}")
}
```

The system property doesn't get printed out.

**Comment by eshepelyuk** [comment]
Could you try following, will it work for you ?

```
project.gatlingRun {
    jvmArgs = [ "-Dfoo.bar=baz" ]
}
```

**Comment by mattweber** [comment]
Same issue here and setting the args in `gatlingRun` doesn't work.  Only workaround is setting the system property when executing gradle: `gradle -Dfoo.bar=baz gatlingRun`  (see #23).

**Comment by AurelienR** [comment]
+1 for the issue

**Comment by adamdougal** [comment]
Hey, I was just wondering if there was a fix coming for this at all?

**Comment by eshepelyuk** [comment]
Hi, sorry for delays. As soon as issue with publishing latest version will be solved - we could try to take a look at this.
The good thing about the issue - there's functioning workaround described above.

**Comment by shavo007** [comment]
@mattweber  how do you access the prop foo.bar  in gatling? does seem to work for us.

**Comment by canthony** [comment]
I am also encountering this same issue. I believe that the jvmArgs *are* getting passed through to the gatlingRun (e.g. -Xmx, -Xmx, -showversion) but that system properties are *not*. e.g.
```
gatling {
 jvmArgs = ["-showversion", "-Dname=value"]
}
```
This will show the JRE version being used by the gatlingRun tasks, but the "name" system variable is *not* being set.

It appears this is because Gradle removes system properties from the jvmArgs and uses the systemProperties, um, property on the JavaExec

So in [GatlingRunTask](https://github.com/lkishalmi/gradle-gatling-plugin/blob/master/src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingRunTask.groovy#L63) we are passing through a map of SystemProperties - and those are used *instead* of those in jvmArgs.

I believe that to fix this, we need to introduce a systemProperties map on the gatling configuration block, and merge those into the GatingRunTask's systemProperties map...

**Comment by spirosag** [comment]
If I understood correctly, passing arguments this way:
```
gatling {
 jvmArgs = ['-Dname=value']
}

```
still isn't working. Correct?

**Comment by eshepelyuk** [comment]
Long time issue, sorry for this huge delay.
I was able to create a test for this and thus will be able to start working on it.
Hope fix will take a little.

**Comment by spirosag** [comment]
No worries! Thanks for the effort! I will upgrade and report back
