### ISSUE TITLE
Gatling directory layout and documentation updates

### ISSUE THREAD

**Issue by eshepelyuk** [lkishalmi/gradle-gatling-plugin#7]
As a next step for PR #6 I'm creating this issue to address following.

1. Introduce new boolean parameter `gatlingDirectoryLayout` to `gatling` extension object that will force _old_ directory layout usage
1. Create new tests for `gatlingDirectoryLayout` parameter
1. Adjust plugin `README` to reflect latest plugin changes. As a part of documentation changes I propose to migrate `README` to [`AsciiDoc` format](http://asciidoctor.org/) 

@lkishalmi please provide feedback on my intentions before I start working on them.

**Comment by lkishalmi** [comment]
I would check the actual layout on disk with a few if to determine which layout is being used rather than add another option to configure. So if you have ```src/gatling/scala``` and ```src/gatling/resources``` then let's go with maven style and if you have ```src/gatling/scenarioes```, ```src/gatling/data``` and ```src/gatling/bodies``` then go with the gatling way. If none of these fits then probably rely on the user to configure its own gatling sourceSet. Tha later one might can be a bit more difficult to implement in the right place, so itcuold be just skipped for now.

As of point 3. Let separate that issue from this. For me that's fine as long as github supports that.

**Comment by eshepelyuk** [comment]
Ok, I'll try to implement as you've suggested. Thanks !
