### ISSUE TITLE
location of JSON files in src/gatling/resources/bodies default removal not clearly documented.

### ISSUE THREAD

**Issue by medikent** [lkishalmi/gradle-gatling-plugin#74]
It appears that older versions of Gatling assumed the JSON files used as `ElFileBody` instances would be sourced from src/gatling/resources/bodies and that the latest version, 3.0.1, no longer makes that assumption. As such my code that used to work in 0.7.4.

`.body(ElFileBody("NewUserTemplate.json"))`

Does not work in 3.0.1. The code that does work in 3.0.1 is:

`.body(ElFileBody("bodies/NewUserTemplate.json"))`

A simple documentation PR will fix this.

**Comment by eshepelyuk** [comment]
Gatling 3.0 doesn't have a notion of bodies and feeders anymore, instead has a resources that can be used from corresponding folder so the plugin does. 

The breaking changes to the source files layout are announced in the top of the docs.

I'm not sure the such evident changes should be put into general documentation since it may overwhelm it with amount of information. 

Closing for now. Plz feel free to feedback if you have more to discuss

**Comment by medikent** [comment]
It seems such changes should be placed at least in a migration guide from 0.7.4 or 0.7.3 to 3.0+ since doing so would help users of older versions to upgrade.

The cheat sheet still shows feeders: https://gatling.io/docs/current/cheat-sheet/ so it seems Gatling 3.0 still has a notion of feeders.

**Comment by medikent** [comment]
Issue 3398 https://github.com/gatling/gatling/issues/3398 does show the bodies and data directories being dropped in favor of the resources directory.

**Comment by eshepelyuk** [comment]
Seems **cheat-sheet** information telling `under the data folder` is outdated since gatling/gatling#3398 clearly describes that special treating of `data` folder is dropped.

I'm ready to accept a PR with a links to `Gatling` changelog / issues explaning the resouce location changes. But since plugin starting from 3.x just began to follow `Gatling` own conventions, there's no reasons to describe migration path separately for the plugin itself.
